workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - build
  - read

build:
  stage: build
  image: ubuntu:latest

  before_script:
    - apt-get update -y
    - apt-get install -y git

  script:
    - echo "Hello, world!"
    - ls -laRt

reading-files:
  stage: read
  image: ubuntu:latest

  before_script:
    - apt-get update -y
    - apt-get install -y git

  script:
    - echo "Hello, world! push"
    - cat testing.txt